### ISSUE TITLE
 : Urgent: Current work plan

### ISSUE THREAD

**Issue by ZechCal** [ZechCal/SuperNote#1]
- [X] Higher Mathematics

- [ ] Operational Research 

- [ ] Statistics

- [X] Linear Algebra 

- [X] CIS Build Project 

- [ ] SuperNote Plan for quickly reorganized notes in books. 

- [ ]  Bost: A batch operation system only for learning and studying

- [ ] PyAutoPart: Lot of useless component assembled together
